// Comprehensive list of Indian cities, towns, and notable places
// organized by state/territory for maintainability.
// ~1500+ entries covering all states and union territories.

const List<String> indianCities = [
  // ─── ANDHRA PRADESH ───
  "Visakhapatnam, Andhra Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Guntur, Andhra Pradesh",
  "Nellore, Andhra Pradesh",
  "Kurnool, Andhra Pradesh",
  "Rajahmundry, Andhra Pradesh",
  "Tirupati, Andhra Pradesh",
  "Kadapa, Andhra Pradesh",
  "Kakinada, Andhra Pradesh",
  "Anantapur, Andhra Pradesh",
  "Eluru, Andhra Pradesh",
  "Ongole, Andhra Pradesh",
  "Nandyal, Andhra Pradesh",
  "Machilipatnam, Andhra Pradesh",
  "Adoni, Andhra Pradesh",
  "Tenali, Andhra Pradesh",
  "Proddatur, Andhra Pradesh",
  "Chittoor, Andhra Pradesh",
  "Hindupur, Andhra Pradesh",
  "Bhimavaram, Andhra Pradesh",
  "Madanapalle, Andhra Pradesh",
  "Guntakal, Andhra Pradesh",
  "Srikakulam, Andhra Pradesh",
  "Dharmavaram, Andhra Pradesh",
  "Gudivada, Andhra Pradesh",
  "Narasaraopet, Andhra Pradesh",
  "Tadipatri, Andhra Pradesh",
  "Kavali, Andhra Pradesh",
  "Tadepalligudem, Andhra Pradesh",
  "Amaravati, Andhra Pradesh",
  "Amalapuram, Andhra Pradesh",
  "Parvathipuram, Andhra Pradesh",
  "Markapur, Andhra Pradesh",
  "Chilakaluripet, Andhra Pradesh",
  "Bapatla, Andhra Pradesh",
  "Narsipatnam, Andhra Pradesh",
  "Chirala, Andhra Pradesh",
  "Vinukonda, Andhra Pradesh",
  "Palasa, Andhra Pradesh",
  "Peddapuram, Andhra Pradesh",
  "Bobbili, Andhra Pradesh",
  "Vijayanagaram, Andhra Pradesh",
  "Mangalagiri, Andhra Pradesh",
  "Sattenapalle, Andhra Pradesh",
  "Repalle, Andhra Pradesh",

  // ─── ARUNACHAL PRADESH ───
  "Itanagar, Arunachal Pradesh",
  "Naharlagun, Arunachal Pradesh",
  "Pasighat, Arunachal Pradesh",
  "Tawang, Arunachal Pradesh",
  "Ziro, Arunachal Pradesh",
  "Bomdila, Arunachal Pradesh",
  "Along, Arunachal Pradesh",
  "Tezu, Arunachal Pradesh",
  "Roing, Arunachal Pradesh",
  "Daporijo, Arunachal Pradesh",

  // ─── ASSAM ───
  "Guwahati, Assam",
  "Silchar, Assam",
  "Dibrugarh, Assam",
  "Jorhat, Assam",
  "Nagaon, Assam",
  "Tinsukia, Assam",
  "Bongaigaon, Assam",
  "Tezpur, Assam",
  "Karimganj, Assam",
  "Hailakandi, Assam",
  "Diphu, Assam",
  "Goalpara, Assam",
  "North Lakhimpur, Assam",
  "Dhubri, Assam",
  "Kokrajhar, Assam",
  "Golaghat, Assam",
  "Sibsagar, Assam",
  "Nalbari, Assam",
  "Barpeta, Assam",
  "Mangaldoi, Assam",
  "Haflong, Assam",
  "Morigaon, Assam",
  "Hojai, Assam",
  "Duliajan, Assam",
  "Majuli, Assam",

  // ─── BIHAR ───
  "Patna, Bihar",
  "Gaya, Bihar",
  "Bhagalpur, Bihar",
  "Muzaffarpur, Bihar",
  "Darbhanga, Bihar",
  "Bihar Sharif, Bihar",
  "Purnia, Bihar",
  "Arrah, Bihar",
  "Begusarai, Bihar",
  "Katihar, Bihar",
  "Munger, Bihar",
  "Saharsa, Bihar",
  "Sasaram, Bihar",
  "Hajipur, Bihar",
  "Dehri, Bihar",
  "Siwan, Bihar",
  "Bettiah, Bihar",
  "Motihari, Bihar",
  "Danapur, Bihar",
  "Chapra, Bihar",
  "Samastipur, Bihar",
  "Buxar, Bihar",
  "Jehanabad, Bihar",
  "Aurangabad, Bihar",
  "Lakhisarai, Bihar",
  "Nawada, Bihar",
  "Madhubani, Bihar",
  "Sitamarhi, Bihar",
  "Jamalpur, Bihar",
  "Supaul, Bihar",
  "Kishanganj, Bihar",
  "Gopalganj, Bihar",
  "Rajgir, Bihar",
  "Bodhgaya, Bihar",
  "Nalanda, Bihar",
  "Madhepura, Bihar",
  "Sheikhpura, Bihar",
  "Khagaria, Bihar",
  "Banka, Bihar",
  "Araria, Bihar",
  "Forbesganj, Bihar",
  "Hilsa, Bihar",
  "Mokama, Bihar",

  // ─── CHHATTISGARH ───
  "Raipur, Chhattisgarh",
  "Bhilai, Chhattisgarh",
  "Bilaspur, Chhattisgarh",
  "Korba, Chhattisgarh",
  "Durg, Chhattisgarh",
  "Rajnandgaon, Chhattisgarh",
  "Jagdalpur, Chhattisgarh",
  "Raigarh, Chhattisgarh",
  "Ambikapur, Chhattisgarh",
  "Mahasamund, Chhattisgarh",
  "Dhamtari, Chhattisgarh",
  "Chirmiri, Chhattisgarh",
  "Kawardha, Chhattisgarh",
  "Dalli Rajhara, Chhattisgarh",
  "Dongargarh, Chhattisgarh",

  // ─── GOA ───
  "Panaji, Goa",
  "Margao, Goa",
  "Vasco Da Gama, Goa",
  "Mapusa, Goa",
  "Ponda, Goa",
  "Bicholim, Goa",
  "Curchorem, Goa",
  "Cuncolim, Goa",
  "Valpoi, Goa",
  "Sanquelim, Goa",
  "Calangute, Goa",
  "Anjuna, Goa",
  "Baga, Goa",
  "Candolim, Goa",
  "Colva, Goa",
  "Palolem, Goa",

  // ─── GUJARAT ───
  "Ahmedabad, Gujarat",
  "Surat, Gujarat",
  "Vadodara, Gujarat",
  "Rajkot, Gujarat",
  "Bhavnagar, Gujarat",
  "Jamnagar, Gujarat",
  "Junagadh, Gujarat",
  "Gandhinagar, Gujarat",
  "Gandhidham, Gujarat",
  "Morbi, Gujarat",
  "Nadiad, Gujarat",
  "Surendranagar Dudhrej, Gujarat",
  "Anand, Gujarat",
  "Navsari, Gujarat",
  "Mehsana, Gujarat",
  "Bharuch, Gujarat",
  "Porbandar, Gujarat",
  "Godhra, Gujarat",
  "Veraval, Gujarat",
  "Patan, Gujarat",
  "Botad, Gujarat",
  "Dahod, Gujarat",
  "Amreli, Gujarat",
  "Palanpur, Gujarat",
  "Valsad, Gujarat",
  "Vapi, Gujarat",
  "Gondal, Gujarat",
  "Diu, Gujarat",
  "Daman, Gujarat",
  "Dwarka, Gujarat",
  "Bhuj, Gujarat",
  "Mandvi, Gujarat",
  "Khambhat, Gujarat",
  "Modasa, Gujarat",
  "Deesa, Gujarat",
  "Jetpur, Gujarat",
  "Kalol, Gujarat",
  "Mahuva, Gujarat",
  "Unjha, Gujarat",
  "Viramgam, Gujarat",
  "Halvad, Gujarat",
  "Somnath, Gujarat",
  "Kutch, Gujarat",
  "Saputara, Gujarat",
  "Gir Forest, Gujarat",
  "Statue of Unity, Gujarat",

  // ─── HARYANA ───
  "Faridabad, Haryana",
  "Gurgaon, Haryana",
  "Panipat, Haryana",
  "Ambala, Haryana",
  "Yamunanagar, Haryana",
  "Rohtak, Haryana",
  "Hisar, Haryana",
  "Karnal, Haryana",
  "Sonipat, Haryana",
  "Panchkula, Haryana",
  "Bhiwani, Haryana",
  "Sirsa, Haryana",
  "Jind, Haryana",
  "Thanesar, Haryana",
  "Kaithal, Haryana",
  "Palwal, Haryana",
  "Rewari, Haryana",
  "Bahadurgarh, Haryana",
  "Hansi, Haryana",
  "Narnaul, Haryana",
  "Fatehabad, Haryana",
  "Mahendragarh, Haryana",
  "Hodal, Haryana",
  "Sohna, Haryana",
  "Manesar, Haryana",
  "Kurukshetra, Haryana",
  "Pinjore, Haryana",
  "Morni Hills, Haryana",
  "Surajkund, Haryana",

  // ─── HIMACHAL PRADESH ───
  "Shimla, Himachal Pradesh",
  "Dharamshala, Himachal Pradesh",
  "Manali, Himachal Pradesh",
  "Solan, Himachal Pradesh",
  "Mandi, Himachal Pradesh",
  "Kullu, Himachal Pradesh",
  "Hamirpur, Himachal Pradesh",
  "Una, Himachal Pradesh",
  "Bilaspur, Himachal Pradesh",
  "Chamba, Himachal Pradesh",
  "Nahan, Himachal Pradesh",
  "Palampur, Himachal Pradesh",
  "Dalhousie, Himachal Pradesh",
  "Sundernagar, Himachal Pradesh",
  "Kasauli, Himachal Pradesh",
  "Spiti Valley, Himachal Pradesh",
  "Lahaul, Himachal Pradesh",
  "Keylong, Himachal Pradesh",
  "Kinnaur, Himachal Pradesh",
  "Kufri, Himachal Pradesh",
  "McLeod Ganj, Himachal Pradesh",
  "Bir Billing, Himachal Pradesh",
  "Barog, Himachal Pradesh",
  "Tirthan Valley, Himachal Pradesh",
  "Jibhi, Himachal Pradesh",
  "Sangla, Himachal Pradesh",
  "Chitkul, Himachal Pradesh",
  "Manikaran, Himachal Pradesh",
  "Rohtang Pass, Himachal Pradesh",
  "Sissu, Himachal Pradesh",
  "Solang Valley, Himachal Pradesh",

  // ─── JHARKHAND ───
  "Ranchi, Jharkhand",
  "Jamshedpur, Jharkhand",
  "Dhanbad, Jharkhand",
  "Bokaro, Jharkhand",
  "Deoghar, Jharkhand",
  "Hazaribagh, Jharkhand",
  "Giridih, Jharkhand",
  "Ramgarh, Jharkhand",
  "Phusro, Jharkhand",
  "Mango, Jharkhand",
  "Medininagar, Jharkhand",
  "Chaibasa, Jharkhand",
  "Dumka, Jharkhand",
  "Chatra, Jharkhand",
  "Gumla, Jharkhand",
  "Lohardaga, Jharkhand",
  "Koderma, Jharkhand",
  "Godda, Jharkhand",
  "Netarhat, Jharkhand",
  "Parasnath, Jharkhand",

  // ─── KARNATAKA ───
  "Bengaluru, Karnataka",
  "Mysore, Karnataka",
  "Hubli-Dharwad, Karnataka",
  "Mangalore, Karnataka",
  "Belgaum, Karnataka",
  "Gulbarga, Karnataka",
  "Davanagere, Karnataka",
  "Bellary, Karnataka",
  "Bijapur, Karnataka",
  "Shimoga, Karnataka",
  "Tumkur, Karnataka",
  "Raichur, Karnataka",
  "Bidar, Karnataka",
  "Hospet, Karnataka",
  "Udupi, Karnataka",
  "Gadag, Karnataka",
  "Hassan, Karnataka",
  "Mandya, Karnataka",
  "Chitradurga, Karnataka",
  "Kolar, Karnataka",
  "Chikmagalur, Karnataka",
  "Bagalkot, Karnataka",
  "Ranibennur, Karnataka",
  "Gangavati, Karnataka",
  "Robertson Pet, Karnataka",
  "Bhadravathi, Karnataka",
  "Nanjangud, Karnataka",
  "Chamarajanagar, Karnataka",
  "Madikeri, Karnataka",
  "Coorg, Karnataka",
  "Hampi, Karnataka",
  "Gokarna, Karnataka",
  "Badami, Karnataka",
  "Aihole, Karnataka",
  "Pattadakal, Karnataka",
  "Bandipur, Karnataka",
  "Kabini, Karnataka",
  "Nagarhole, Karnataka",
  "Dandeli, Karnataka",
  "Murudeshwar, Karnataka",
  "Jog Falls, Karnataka",
  "Yana, Karnataka",
  "Sakleshpur, Karnataka",
  "Ramanagara, Karnataka",

  // ─── KERALA ───
  "Thiruvananthapuram, Kerala",
  "Kochi, Kerala",
  "Kozhikode, Kerala",
  "Kollam, Kerala",
  "Thrissur, Kerala",
  "Alappuzha, Kerala",
  "Kottayam, Kerala",
  "Palakkad, Kerala",
  "Kannur, Kerala",
  "Kasaragod, Kerala",
  "Malappuram, Kerala",
  "Pathanamthitta, Kerala",
  "Idukki, Kerala",
  "Wayanad, Kerala",
  "Ernakulam, Kerala",
  "Thalassery, Kerala",
  "Munnar, Kerala",
  "Thekkady, Kerala",
  "Kumarakom, Kerala",
  "Varkala, Kerala",
  "Kovalam, Kerala",
  "Marari, Kerala",
  "Athirappilly, Kerala",
  "Bekal, Kerala",
  "Fort Kochi, Kerala",
  "Vagamon, Kerala",
  "Ponmudi, Kerala",
  "Guruvayur, Kerala",
  "Periyar, Kerala",
  "Poovar, Kerala",
  "Cherai, Kerala",

  // ─── MADHYA PRADESH ───
  "Indore, Madhya Pradesh",
  "Bhopal, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Ujjain, Madhya Pradesh",
  "Sagar, Madhya Pradesh",
  "Satna, Madhya Pradesh",
  "Dewas, Madhya Pradesh",
  "Ratlam, Madhya Pradesh",
  "Rewa, Madhya Pradesh",
  "Katni, Madhya Pradesh",
  "Singrauli, Madhya Pradesh",
  "Burhanpur, Madhya Pradesh",
  "Khandwa, Madhya Pradesh",
  "Morena, Madhya Pradesh",
  "Bhind, Madhya Pradesh",
  "Guna, Madhya Pradesh",
  "Shivpuri, Madhya Pradesh",
  "Vidisha, Madhya Pradesh",
  "Chhindwara, Madhya Pradesh",
  "Damoh, Madhya Pradesh",
  "Mandsaur, Madhya Pradesh",
  "Hoshangabad, Madhya Pradesh",
  "Itarsi, Madhya Pradesh",
  "Sehore, Madhya Pradesh",
  "Betul, Madhya Pradesh",
  "Seoni, Madhya Pradesh",
  "Datia, Madhya Pradesh",
  "Nagda, Madhya Pradesh",
  "Neemuch, Madhya Pradesh",
  "Tikamgarh, Madhya Pradesh",
  "Shahdol, Madhya Pradesh",
  "Pithampur, Madhya Pradesh",
  "Dhar, Madhya Pradesh",
  "Mhow, Madhya Pradesh",
  "Mandla, Madhya Pradesh",
  "Khajuraho, Madhya Pradesh",
  "Orchha, Madhya Pradesh",
  "Pachmarhi, Madhya Pradesh",
  "Sanchi, Madhya Pradesh",
  "Mandu, Madhya Pradesh",
  "Panna, Madhya Pradesh",
  "Kanha, Madhya Pradesh",
  "Bandhavgarh, Madhya Pradesh",
  "Pench, Madhya Pradesh",
  "Omkareshwar, Madhya Pradesh",
  "Maheshwar, Madhya Pradesh",

  // ─── MAHARASHTRA ───
  "Mumbai, Maharashtra",
  "Pune, Maharashtra",
  "Nagpur, Maharashtra",
  "Thane, Maharashtra",
  "Pimpri-Chinchwad, Maharashtra",
  "Nashik, Maharashtra",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Aurangabad, Maharashtra",
  "Navi Mumbai, Maharashtra",
  "Solapur, Maharashtra",
  "Mira-Bhayandar, Maharashtra",
  "Bhiwandi, Maharashtra",
  "Amravati, Maharashtra",
  "Nanded, Maharashtra",
  "Kolhapur, Maharashtra",
  "Akola, Maharashtra",
  "Ulhasnagar, Maharashtra",
  "Sangli-Miraj & Kupwad, Maharashtra",
  "Malegaon, Maharashtra",
  "Jalgaon, Maharashtra",
  "Ambarnath, Maharashtra",
  "Latur, Maharashtra",
  "Dhule, Maharashtra",
  "Ahmednagar, Maharashtra",
  "Ichalkaranji, Maharashtra",
  "Chandrapur, Maharashtra",
  "Parbhani, Maharashtra",
  "Jalna, Maharashtra",
  "Bhusawal, Maharashtra",
  "Panvel, Maharashtra",
  "Satara, Maharashtra",
  "Beed, Maharashtra",
  "Yavatmal, Maharashtra",
  "Kamptee, Maharashtra",
  "Gondiya, Maharashtra",
  "Barshi, Maharashtra",
  "Wardha, Maharashtra",
  "Osmanabad, Maharashtra",
  "Amalner, Maharashtra",
  "Nandurbar, Maharashtra",
  "Washim, Maharashtra",
  "Hinganghat, Maharashtra",
  "Ratnagiri, Maharashtra",
  "Sindhudurg, Maharashtra",
  "Shirdi, Maharashtra",
  "Lonavala, Maharashtra",
  "Mahabaleshwar, Maharashtra",
  "Matheran, Maharashtra",
  "Alibaug, Maharashtra",
  "Khandala, Maharashtra",
  "Lavasa, Maharashtra",
  "Panchgani, Maharashtra",
  "Ganpatipule, Maharashtra",
  "Harihareshwar, Maharashtra",
  "Ajanta, Maharashtra",
  "Ellora, Maharashtra",
  "Tadoba, Maharashtra",
  "Bhimashankar, Maharashtra",
  "Trimbakeshwar, Maharashtra",

  // ─── MANIPUR ───
  "Imphal, Manipur",
  "Thoubal, Manipur",
  "Bishnupur, Manipur",
  "Churachandpur, Manipur",
  "Ukhrul, Manipur",
  "Senapati, Manipur",
  "Tamenglong, Manipur",
  "Moreh, Manipur",
  "Kakching, Manipur",
  "Loktak Lake, Manipur",

  // ─── MEGHALAYA ───
  "Shillong, Meghalaya",
  "Tura, Meghalaya",
  "Jowai, Meghalaya",
  "Nongstoin, Meghalaya",
  "Williamnagar, Meghalaya",
  "Cherrapunji, Meghalaya",
  "Mawlynnong, Meghalaya",
  "Dawki, Meghalaya",
  "Nongpoh, Meghalaya",
  "Mawsynram, Meghalaya",
  "Living Root Bridges, Meghalaya",

  // ─── MIZORAM ───
  "Aizawl, Mizoram",
  "Lunglei, Mizoram",
  "Champhai, Mizoram",
  "Serchhip, Mizoram",
  "Kolasib, Mizoram",
  "Lawngtlai, Mizoram",
  "Saiha, Mizoram",
  "Mamit, Mizoram",
  "Phawngpui, Mizoram",

  // ─── NAGALAND ───
  "Kohima, Nagaland",
  "Dimapur, Nagaland",
  "Mokokchung, Nagaland",
  "Tuensang, Nagaland",
  "Wokha, Nagaland",
  "Zunheboto, Nagaland",
  "Mon, Nagaland",
  "Phek, Nagaland",
  "Peren, Nagaland",
  "Longleng, Nagaland",
  "Kiphire, Nagaland",
  "Dzukou Valley, Nagaland",

  // ─── ODISHA ───
  "Bhubaneswar, Odisha",
  "Cuttack, Odisha",
  "Rourkela, Odisha",
  "Berhampur, Odisha",
  "Sambalpur, Odisha",
  "Raurkela Industrial Township, Odisha",
  "Puri, Odisha",
  "Balasore, Odisha",
  "Baripada, Odisha",
  "Bhadrak, Odisha",
  "Jharsuguda, Odisha",
  "Bargarh, Odisha",
  "Angul, Odisha",
  "Dhenkanal, Odisha",
  "Keonjhar, Odisha",
  "Jeypore, Odisha",
  "Rayagada, Odisha",
  "Koraput, Odisha",
  "Paradip, Odisha",
  "Sundargarh, Odisha",
  "Kendujhar, Odisha",
  "Konark, Odisha",
  "Chilika, Odisha",
  "Simlipal, Odisha",
  "Chandipur, Odisha",
  "Gopalpur, Odisha",
  "Bhitarkanika, Odisha",
  "Daringbadi, Odisha",

  // ─── PUNJAB ───
  "Ludhiana, Punjab",
  "Amritsar, Punjab",
  "Jalandhar, Punjab",
  "Patiala, Punjab",
  "Bathinda, Punjab",
  "Phagwara, Punjab",
  "Mohali, Punjab",
  "Pathankot, Punjab",
  "Hoshiarpur, Punjab",
  "Batala, Punjab",
  "Moga, Punjab",
  "Abohar, Punjab",
  "Malerkotla, Punjab",
  "Khanna, Punjab",
  "Muktsar, Punjab",
  "Barnala, Punjab",
  "Rajpura, Punjab",
  "Firozpur, Punjab",
  "Kapurthala, Punjab",
  "Faridkot, Punjab",
  "Sangrur, Punjab",
  "Fazilka, Punjab",
  "Gurdaspur, Punjab",
  "Ropar, Punjab",
  "Nawanshahr, Punjab",
  "Mansa, Punjab",
  "Sultanpur Lodhi, Punjab",
  "Anandpur Sahib, Punjab",
  "Dera Baba Nanak, Punjab",

  // ─── RAJASTHAN ───
  "Jaipur, Rajasthan",
  "Jodhpur, Rajasthan",
  "Udaipur, Rajasthan",
  "Kota, Rajasthan",
  "Bikaner, Rajasthan",
  "Ajmer, Rajasthan",
  "Bhilwara, Rajasthan",
  "Alwar, Rajasthan",
  "Bharatpur, Rajasthan",
  "Sikar, Rajasthan",
  "Pali, Rajasthan",
  "Sri Ganganagar, Rajasthan",
  "Tonk, Rajasthan",
  "Beawar, Rajasthan",
  "Hanumangarh, Rajasthan",
  "Dhaulpur, Rajasthan",
  "Gangapur City, Rajasthan",
  "Sawai Madhopur, Rajasthan",
  "Churu, Rajasthan",
  "Jhunjhunu, Rajasthan",
  "Chittorgarh, Rajasthan",
  "Nagaur, Rajasthan",
  "Bundi, Rajasthan",
  "Barmer, Rajasthan",
  "Jaisalmer, Rajasthan",
  "Pushkar, Rajasthan",
  "Mount Abu, Rajasthan",
  "Ranthambore, Rajasthan",
  "Neemrana, Rajasthan",
  "Mandawa, Rajasthan",
  "Bhangarh, Rajasthan",
  "Nathdwara, Rajasthan",
  "Ranakpur, Rajasthan",
  "Kumbhalgarh, Rajasthan",
  "Sariska, Rajasthan",
  "Shekhawati, Rajasthan",
  "Sambhar, Rajasthan",
  "Osian, Rajasthan",
  "Deeg, Rajasthan",
  "Dungarpur, Rajasthan",
  "Banswara, Rajasthan",
  "Pratapgarh, Rajasthan",
  "Jhalawar, Rajasthan",
  "Rajsamand, Rajasthan",
  "Karauli, Rajasthan",

  // ─── SIKKIM ───
  "Gangtok, Sikkim",
  "Namchi, Sikkim",
  "Mangan, Sikkim",
  "Gyalshing, Sikkim",
  "Rangpo, Sikkim",
  "Jorethang, Sikkim",
  "Pelling, Sikkim",
  "Ravangla, Sikkim",
  "Lachung, Sikkim",
  "Lachen, Sikkim",
  "Yuksom, Sikkim",
  "Zuluk, Sikkim",
  "Tsomgo Lake, Sikkim",
  "Nathula Pass, Sikkim",
  "Gurudongmar Lake, Sikkim",

  // ─── TAMIL NADU ───
  "Chennai, Tamil Nadu",
  "Coimbatore, Tamil Nadu",
  "Madurai, Tamil Nadu",
  "Tiruchirappalli, Tamil Nadu",
  "Salem, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Tirupur, Tamil Nadu",
  "Erode, Tamil Nadu",
  "Vellore, Tamil Nadu",
  "Thoothukudi, Tamil Nadu",
  "Dindigul, Tamil Nadu",
  "Thanjavur, Tamil Nadu",
  "Nagercoil, Tamil Nadu",
  "Avadi, Tamil Nadu",
  "Ambattur, Tamil Nadu",
  "Pallavaram, Tamil Nadu",
  "Tiruvottiyur, Tamil Nadu",
  "Pudukkottai, Tamil Nadu",
  "Hosur, Tamil Nadu",
  "Kumbakonam, Tamil Nadu",
  "Cuddalore, Tamil Nadu",
  "Karur, Tamil Nadu",
  "Rajapalayam, Tamil Nadu",
  "Sivakasi, Tamil Nadu",
  "Namakkal, Tamil Nadu",
  "Vaniyambadi, Tamil Nadu",
  "Tiruvannamalai, Tamil Nadu",
  "Pollachi, Tamil Nadu",
  "Kanchipuram, Tamil Nadu",
  "Mahabalipuram, Tamil Nadu",
  "Pondicherry, Tamil Nadu",
  "Rameswaram, Tamil Nadu",
  "Kanyakumari, Tamil Nadu",
  "Ooty, Tamil Nadu",
  "Kodaikanal, Tamil Nadu",
  "Coonoor, Tamil Nadu",
  "Yercaud, Tamil Nadu",
  "Valparai, Tamil Nadu",
  "Yelagiri, Tamil Nadu",
  "Chidambaram, Tamil Nadu",
  "Nagapattinam, Tamil Nadu",
  "Velankanni, Tamil Nadu",
  "Srirangam, Tamil Nadu",
  "Dhanushkodi, Tamil Nadu",
  "Pichavaram, Tamil Nadu",
  "Courtallam, Tamil Nadu",
  "Kolli Hills, Tamil Nadu",
  "Meghamalai, Tamil Nadu",
  "Hogenakkal, Tamil Nadu",
  "Auroville, Tamil Nadu",

  // ─── TELANGANA ───
  "Hyderabad, Telangana",
  "Warangal, Telangana",
  "Nizamabad, Telangana",
  "Karimnagar, Telangana",
  "Khammam, Telangana",
  "Ramagundam, Telangana",
  "Secunderabad, Telangana",
  "Mahbubnagar, Telangana",
  "Suryapet, Telangana",
  "Miryalaguda, Telangana",
  "Mancherial, Telangana",
  "Adilabad, Telangana",
  "Siddipet, Telangana",
  "Nalgonda, Telangana",
  "Medak, Telangana",
  "Sangareddy, Telangana",
  "Jagtial, Telangana",
  "Wanaparthy, Telangana",
  "Gadwal, Telangana",
  "Narayanpet, Telangana",
  "Bhongir, Telangana",
  "Shamshabad, Telangana",

  // ─── TRIPURA ───
  "Agartala, Tripura",
  "Udaipur, Tripura",
  "Dharmanagar, Tripura",
  "Kailashahar, Tripura",
  "Ambassa, Tripura",
  "Belonia, Tripura",
  "Khowai, Tripura",
  "Sabroom, Tripura",
  "Sonamura, Tripura",
  "Neermahal, Tripura",
  "Unakoti, Tripura",

  // ─── UTTAR PRADESH ───
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Ghaziabad, Uttar Pradesh",
  "Agra, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Allahabad, Uttar Pradesh",
  "Bareilly, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Aligarh, Uttar Pradesh",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Noida, Uttar Pradesh",
  "Firozabad, Uttar Pradesh",
  "Loni, Uttar Pradesh",
  "Jhansi, Uttar Pradesh",
  "Muzaffarnagar, Uttar Pradesh",
  "Mathura, Uttar Pradesh",
  "Shahjahanpur, Uttar Pradesh",
  "Rampur, Uttar Pradesh",
  "Sambhal, Uttar Pradesh",
  "Amroha, Uttar Pradesh",
  "Mau, Uttar Pradesh",
  "Hapur, Uttar Pradesh",
  "Etawah, Uttar Pradesh",
  "Mirzapur, Uttar Pradesh",
  "Bulandshahr, Uttar Pradesh",
  "Unnao, Uttar Pradesh",
  "Jaunpur, Uttar Pradesh",
  "Fatehpur, Uttar Pradesh",
  "Raebareli, Uttar Pradesh",
  "Orai, Uttar Pradesh",
  "Bahraich, Uttar Pradesh",
  "Farrukhabad, Uttar Pradesh",
  "Banda, Uttar Pradesh",
  "Mainpuri, Uttar Pradesh",
  "Sultanpur, Uttar Pradesh",
  "Hardoi, Uttar Pradesh",
  "Sitapur, Uttar Pradesh",
  "Lakhimpur Kheri, Uttar Pradesh",
  "Pilibhit, Uttar Pradesh",
  "Basti, Uttar Pradesh",
  "Deoria, Uttar Pradesh",
  "Azamgarh, Uttar Pradesh",
  "Gonda, Uttar Pradesh",
  "Ballia, Uttar Pradesh",
  "Pratapgarh, Uttar Pradesh",
  "Vrindavan, Uttar Pradesh",
  "Ayodhya, Uttar Pradesh",
  "Fatehpur Sikri, Uttar Pradesh",
  "Kushinagar, Uttar Pradesh",
  "Sarnath, Uttar Pradesh",
  "Chitrakoot, Uttar Pradesh",
  "Vindhyachal, Uttar Pradesh",
  "Dudhwa, Uttar Pradesh",
  "Greater Noida, Uttar Pradesh",
  "Ghazipur, Uttar Pradesh",
  "Shravasti, Uttar Pradesh",
  "Barabanki, Uttar Pradesh",
  "Chandauli, Uttar Pradesh",
  "Bijnor, Uttar Pradesh",
  "Kasganj, Uttar Pradesh",
  "Etah, Uttar Pradesh",
  "Hathras, Uttar Pradesh",
  "Auraiya, Uttar Pradesh",
  "Hamirpur, Uttar Pradesh",
  "Lalitpur, Uttar Pradesh",
  "Mahoba, Uttar Pradesh",
  "Sonbhadra, Uttar Pradesh",

  // ─── UTTARAKHAND ───
  "Dehradun, Uttarakhand",
  "Haridwar, Uttarakhand",
  "Haldwani, Uttarakhand",
  "Rishikesh, Uttarakhand",
  "Roorkee, Uttarakhand",
  "Kashipur, Uttarakhand",
  "Rudrapur, Uttarakhand",
  "Nainital, Uttarakhand",
  "Mussoorie, Uttarakhand",
  "Almora, Uttarakhand",
  "Pithoragarh, Uttarakhand",
  "Pauri, Uttarakhand",
  "Tehri, Uttarakhand",
  "Uttarkashi, Uttarakhand",
  "Rudraprayag, Uttarakhand",
  "Chamoli, Uttarakhand",
  "Bageshwar, Uttarakhand",
  "Champawat, Uttarakhand",
  "Lansdowne, Uttarakhand",
  "Ranikhet, Uttarakhand",
  "Kausani, Uttarakhand",
  "Binsar, Uttarakhand",
  "Mukteshwar, Uttarakhand",
  "Chopta, Uttarakhand",
  "Auli, Uttarakhand",
  "Valley of Flowers, Uttarakhand",
  "Kedarnath, Uttarakhand",
  "Badrinath, Uttarakhand",
  "Gangotri, Uttarakhand",
  "Yamunotri, Uttarakhand",
  "Jim Corbett, Uttarakhand",
  "Rajaji, Uttarakhand",
  "Bhimtal, Uttarakhand",
  "Sattal, Uttarakhand",
  "Munsiyari, Uttarakhand",
  "Dhanaulti, Uttarakhand",
  "Chakrata, Uttarakhand",
  "Kanatal, Uttarakhand",
  "Pangot, Uttarakhand",
  "Tungnath, Uttarakhand",
  "Deoriatal, Uttarakhand",
  "Har Ki Dun, Uttarakhand",
  "Roopkund, Uttarakhand",
  "Dayara Bugyal, Uttarakhand",

  // ─── WEST BENGAL ───
  "Kolkata, West Bengal",
  "Howrah, West Bengal",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Siliguri, West Bengal",
  "Maheshtala, West Bengal",
  "Rajpur Sonarpur, West Bengal",
  "South Dumdum, West Bengal",
  "Bhatpara, West Bengal",
  "Panihati, West Bengal",
  "Kamarhati, West Bengal",
  "Bardhaman, West Bengal",
  "Kulti, West Bengal",
  "Bally, West Bengal",
  "Barasat, West Bengal",
  "North Dumdum, West Bengal",
  "Baranagar, West Bengal",
  "Uluberia, West Bengal",
  "Naihati, West Bengal",
  "Bidhan Nagar, West Bengal",
  "Madhyamgram, West Bengal",
  "Berhampore, West Bengal",
  "English Bazar, West Bengal",
  "Raiganj, West Bengal",
  "Haldia, West Bengal",
  "Kharagpur, West Bengal",
  "Serampore, West Bengal",
  "Chinsurah, West Bengal",
  "Nabadwip, West Bengal",
  "Darjeeling, West Bengal",
  "Jalpaiguri, West Bengal",
  "Purulia, West Bengal",
  "Kalimpong, West Bengal",
  "Kalyani, West Bengal",
  "Krishnanagar, West Bengal",
  "Gopalpur, West Bengal",
  "Shantiniketan, West Bengal",
  "Sundarbans, West Bengal",
  "Digha, West Bengal",
  "Mandarmani, West Bengal",
  "Bakkhali, West Bengal",
  "Tajpur, West Bengal",
  "Kurseong, West Bengal",
  "Mirik, West Bengal",
  "Sandakphu, West Bengal",
  "Phalut, West Bengal",
  "Lava, West Bengal",
  "Lolegaon, West Bengal",
  "Jaldapara, West Bengal",
  "Cooch Behar, West Bengal",
  "Malda, West Bengal",
  "Bankura, West Bengal",
  "Midnapore, West Bengal",
  "Tamluk, West Bengal",
  "Contai, West Bengal",
  "Basirhat, West Bengal",
  "Diamond Harbour, West Bengal",
  "Barrackpore, West Bengal",
  "Rishra, West Bengal",
  "Titagarh, West Bengal",
  "Habra, West Bengal",
  "Bangaon, West Bengal",
  "Ranaghat, West Bengal",
  "Santipur, West Bengal",
  "Balurghat, West Bengal",
  "Jangipur, West Bengal",
  "Hooghly, West Bengal",

  // ─── DELHI / NCR ───
  "Delhi, National Capital Territory",
  "New Delhi, National Capital Territory",
  "Karawal Nagar, Delhi",
  "Kirari Suleman Nagar, Delhi",
  "Nangloi Jat, Delhi",
  "Bhalswa Jahangir Pur, Delhi",
  "Sultan Pur Majra, Delhi",
  "Dwarka, Delhi",
  "Rohini, Delhi",
  "Saket, Delhi",
  "Connaught Place, Delhi",
  "Chandni Chowk, Delhi",
  "Hauz Khas, Delhi",
  "Lajpat Nagar, Delhi",
  "Karol Bagh, Delhi",
  "Nehru Place, Delhi",
  "Mehrauli, Delhi",

  // ─── CHANDIGARH ───
  "Chandigarh, Chandigarh",

  // ─── PUDUCHERRY ───
  "Puducherry, Puducherry",
  "Ozhukarai, Puducherry",
  "Karaikal, Puducherry",
  "Mahe, Puducherry",
  "Yanam, Puducherry",

  // ─── JAMMU & KASHMIR ───
  "Srinagar, Jammu and Kashmir",
  "Jammu, Jammu and Kashmir",
  "Anantnag, Jammu and Kashmir",
  "Baramulla, Jammu and Kashmir",
  "Sopore, Jammu and Kashmir",
  "Kathua, Jammu and Kashmir",
  "Udhampur, Jammu and Kashmir",
  "Rajouri, Jammu and Kashmir",
  "Poonch, Jammu and Kashmir",
  "Kupwara, Jammu and Kashmir",
  "Pulwama, Jammu and Kashmir",
  "Shopian, Jammu and Kashmir",
  "Kulgam, Jammu and Kashmir",
  "Bandipore, Jammu and Kashmir",
  "Ganderbal, Jammu and Kashmir",
  "Gulmarg, Jammu and Kashmir",
  "Pahalgam, Jammu and Kashmir",
  "Sonmarg, Jammu and Kashmir",
  "Patnitop, Jammu and Kashmir",
  "Vaishno Devi, Jammu and Kashmir",
  "Amarnath, Jammu and Kashmir",
  "Dal Lake, Jammu and Kashmir",
  "Doodhpathri, Jammu and Kashmir",
  "Yusmarg, Jammu and Kashmir",
  "Kishtwar, Jammu and Kashmir",
  "Bhaderwah, Jammu and Kashmir",
  "Mughal Road, Jammu and Kashmir",

  // ─── LADAKH ───
  "Leh, Ladakh",
  "Kargil, Ladakh",
  "Nubra Valley, Ladakh",
  "Pangong Lake, Ladakh",
  "Tso Moriri, Ladakh",
  "Zanskar, Ladakh",
  "Hemis, Ladakh",
  "Khardung La, Ladakh",
  "Magnetic Hill, Ladakh",
  "Lamayuru, Ladakh",
  "Diskit, Ladakh",
  "Hanle, Ladakh",
  "Turtuk, Ladakh",
  "Drass, Ladakh",

  // ─── ANDAMAN & NICOBAR ISLANDS ───
  "Port Blair, Andaman and Nicobar Islands",
  "Havelock Island, Andaman and Nicobar Islands",
  "Neil Island, Andaman and Nicobar Islands",
  "Ross Island, Andaman and Nicobar Islands",
  "Baratang Island, Andaman and Nicobar Islands",
  "Diglipur, Andaman and Nicobar Islands",
  "Long Island, Andaman and Nicobar Islands",
  "Rangat, Andaman and Nicobar Islands",

  // ─── LAKSHADWEEP ───
  "Kavaratti, Lakshadweep",
  "Agatti, Lakshadweep",
  "Bangaram, Lakshadweep",
  "Minicoy, Lakshadweep",
  "Kalpeni, Lakshadweep",
  "Kadmat, Lakshadweep",

  // ─── DADRA & NAGAR HAVELI AND DAMAN & DIU ───
  "Silvassa, Dadra and Nagar Haveli",
  "Daman, Daman and Diu",
  "Diu, Daman and Diu",
];
